acdlite/recompose

src/__tests__/withState-test.js, src/withState.js
Split
https://github.com/acdlite/recompose/pull/13
=> Add callback to updateStateValue function

.eslintrc, README.md, docs/API.md, src/__tests__/createElement-test.js, src/__tests__/renderComponent-test.js, src/__tests__/renderNothing-test.js, src/createElement.js, src/index.js, src/renderComponent.js, src/renderNothing.js, tests.webpack.js
Adds renderComponent() and renderNothing() helpers, with corresponding docs.
Also adds a section to the README about performance.
=> Add renderComponent(), renderNothing(), and update docs

docs/API.md, src/__tests__/mapPropsOnChange-test.js, src/index.js, src/mapPropsOnChange.js
The word "update" wrongly implies that `shouldComponentUpdate()` is somehow involved.
=> Rename mapPropsOnUpdate -> mapPropsOnChange

docs/API.md, src/__tests__/toClass-test.js, src/index.js, src/toClass.js
Implemented toClass helper function described in #34. Actually, this is something I really wanted! 
Please take a look.
=> toClass helper function

docs/API.md, src/onlyUpdateForProps.js
=> OnlyUpdateForProps

src/packages/rx-recompose/package.json
=> Fix wrong version of recompose

package.json
=> Add devEngines to package.json

src/packages/recompose/__tests__/doOnReceiveProps-test.js, src/packages/recompose/doOnReceiveProps.js
doOnReceiveProps must pass props to BaseComponent
=> doOnReceiveProps fix

src/packages/recompose/toClass.js, src/packages/recompose/withContext.js
Refactors uses of static class props to oldschool style for ie8 Compatibility.
Let me know how you feel about variable names.
=> Remove uses of static class props

docs/API.md
Replaced renameProps with flattenProp
=> Corrected signature of flattenProp

README.md
Add link to blog post by @gaearon explaining the "smart vs dumb component pattern".
=> Add link in README.md to external reference

src/packages/recompose/createElement.js
fix for #112. Hopefully it's helpful.
=> hasKey fix

src/packages/rx-recompose/README.md
Update the README example to match API
=> Update rx-recompose example to match api

src/packages/recompose/__tests__/withProps-test.js, src/packages/recompose/withProps.js
Fix this https://github.com/acdlite/recompose/issues/105#issuecomment-213607329
=> Fix withProps #105

src/packages/recompose/createElement.js, src/packages/recompose/defaultProps.js, src/packages/recompose/flattenProp.js, src/packages/recompose/getContext.js, src/packages/recompose/mapProps.js, src/packages/recompose/nest.js, src/packages/recompose/onlyUpdateForKeys.js, src/packages/recompose/renderComponent.js, src/packages/recompose/shouldUpdate.js, src/packages/recompose/withContext.js, src/packages/recompose/withHandlers.js, src/packages/recompose/withReducer.js, src/packages/recompose/withState.js
See #146.
@nfcampos Want to review?
=> Use "curried" form of createElement internally

package.json, scripts/release.js, src/packages/recompose/componentFromProp.js, src/packages/recompose/flattenProp.js, src/packages/recompose/onlyUpdateForKeys.js, src/packages/recompose/renameProp.js, src/packages/recompose/renameProps.js, src/packages/recompose/utils/omit.js, src/packages/recompose/utils/pick.js, src/packages/recompose/withHandlers.js, src/packages/recompose/withProps.js, src/packages/recompose/withPropsOnChange.js, src/packages/recompose/withReducer.js, src/packages/recompose/withState.js, src/packages/rx-recompose/__tests__/mapPropsStream-test.js, webpack.config.js
Will help close https://github.com/acdlite/recompose/issues/152 and https://github.com/acdlite/recompose/issues/131
=> Build UMD bundle on release

package.json, src/packages/recompose/__tests__/compose-test.js, src/packages/recompose/compose.js, src/packages/recompose/package.json, webpack.config.js
=> Remove remaining lodash dep

src/packages/recompose/createHelper.js
Removed some redundant conditions.
=> Clean up createHelper

src/packages/recompose/__tests__/withHandlers-test.js, src/packages/recompose/withHandlers.js
`withHandlers()` caches handlers after creating them. This prevents a new function from being allocated on each call. The cache is cleared whenever the component receives new props.
=> Cache handlers

docs/API.md, src/packages/recompose/__tests__/lifecycle-test.js, src/packages/recompose/index.js, src/packages/recompose/lifecycle.js
=> Add back lifecycle() as wrapper around React.createClass

src/packages/rx-recompose/__tests__/mapPropsStream-test.js, src/packages/rx-recompose/createComponent.js, src/packages/rx-recompose/createEventHandler.js, src/packages/rx-recompose/package.json
Should close https://github.com/acdlite/recompose/issues/158. Need test to confirm before merging.
=> Use change-emitter to keep track of observers

docs/API.md
=> Add "TOC" to API document

README.md
I found 404 link rx-recompose.
=> Remove rx-recompose link

docs/API.md
changed `... an prop ...` to `... a prop ...`
=> Grammar fix in API documentation

src/packages/recompose/rxjs4ObservableConfig.js
Another bugfix related to observables
=> Wrap subscription inside closure to maintain context

docs/API.md
=> Fix createEventHandler anchor

docs/API.md
Clarifies how hoistStatics works, see #253
=> Add details about static types that will not be hoisted with hoistSatics

README.md
I've just copy the words from [Redux](https://github.com/reactjs/redux/blob/master/CONTRIBUTING.md) and renamed Redux to Recompose.
Closed #239
=> Add Getting Help section in README.md

README.md
Addresses: https://github.com/acdlite/recompose/issues/263
Add usage of https://github.com/lodash/babel-plugin-lodash for bundle size improvement.
=> Add docs for usage with babel-plugin-lodash

src/packages/recompose/withHandlers.js
- Remove an unused variable `i`
- Change `result` to `{}` instead of `[]`
=> Refactor mapValues used in withHandlers

src/packages/recompose/__tests__/componentFromStream-test.skip.js, src/packages/recompose/componentFromStream.js
=> Сomplete props stream before unmounting.

docs/API.md
What is the difference between `withHandlers` and  `withProps` has been frequently asked. See [SO](http://stackoverflow.com/questions/42590958/withprops-vs-withhandlers) and #315. This PR is aim to clarify this question.
=> Update README.md to promote using withHandlers

docs/API.md
- Add example for renderNothing
- improve example for renderComponent
- Clarify optional param for branch
=> Update branch related docs

docs/API.md
=> update API docs 

package.json, src/packages/recompose/__tests__/withHandlers-test.js
new installation requirements for enzyme with React >= 15.5 https://github.com/airbnb/enzyme#installation
=> Fix tests.

src/packages/recompose/pure.js
=> Fix pure enhancer

README.md
I added several recipes to the page to get it kick started!
=> Add "Recipes" section to README

README.md
Clicked it and it led nowhere :(
=> remove discord channel

types/flow-typed/recompose_v0.24.x-/flow_v0.49.x-/recompose_v0.24.x-.js
=> Expose Component type

types/flow-typed/recompose_v0.24.x/flow_v0.53.x-/test_classBasedEnhancer.js, types/flow-typed/recompose_v0.24.x/flow_v0.53.x-/test_functionalEnhancer.js
Also can be used as examples how to create your own enhancers with flow
=> Add flow tests for user enhancers in flow libdef

README.md
In response to https://github.com/acdlite/recompose/issues/458#issuecomment-326126729.
=> Add note about preact usage

types/flow-example/package.json, types/flow-example/yarn.lock, types/flow-typed/package.json, types/flow-typed/recompose_v0.24.x/flow_v0.53.x-/recompose_v0.24.x.js, types/flow-typed/recompose_v0.24.x/flow_v0.53.x-/test_withStateHandlers.js, types/flow-typed/yarn.lock
=> Fix withState handlers definition for defined type of state

docs/API.md, src/packages/recompose/index.js
Address issue #520. I'll also suggest a separate PR for typescript types in the appropriate repo.
=> export `createEventHandlerWithConfig()` and add documentation.

README.md
As title. It might be useful for new comers.
=> Add a debugging section in README

README.md, docs/performance.md
I am not sure if we want to remove `performance.md` completely or just the outdated part.
Fixing #614
=> Update docs & readme

docs/API.md
This adds docs for https://github.com/acdlite/recompose/pull/632. (As discussed in https://github.com/acdlite/recompose/pull/632#issuecomment-376198939)
=> Add blacklist docs for hoistStatics

docs/API.md
Following the issue #337, I've decided add examples for renameProp and renameProps.
=> Add examples for renameProp and renameProps
