- README.md
Now showing current count (not total number of clicks which may have been the intent?).
> Fix to "Quick example: Counter", was not outputting any data. 

- README.md
Removed property "counter" from mapProps (is supplied by ...rest).
> Fix to "Quick example: Counter", not working

- src/__tests__/defaultProps-test.js
- src/defaultProps.js
Slit this https://github.com/acdlite/recompose/pull/13
Also move props 2 defaultProps as React do
> defaultProps overrides undefined props from owner

- src/branch.js
- src/createElement.js
- src/defaultProps.js
- src/doOnReceiveProps.js
- src/flattenProp.js
- src/getContext.js
- src/isStatelessFunctionComponent.js
- src/lifecycle.js
- src/mapProps.js
- src/mapPropsOnUpdate.js
- src/shouldUpdate.js
- src/withContext.js
- src/withProps.js
- src/withReducer.js
- src/withState.js
Adds a replacement for `React.createElement(Component, props)` which checks if the component is a stateless function. If so, it calls the function rather than creating an intermediate React element, hashtag referential transparency.
Used internally, but not exposed publicly since React will presumably optimize for stateless function components soon.
> Avoid unnecessary intermediate elements by calling function components instead of using React.createElement()

- src/__tests__/defaultProps-test.js
- src/defaultProps.js
defaultProps doesn't work in combination with other recompose hoc (only if defined first in chain)
> Fail test for defaultProps

- src/__tests__/isReferentiallyTransparentFunctionComponent-test.js
- src/isReferentiallyTransparentFunctionComponent.js
Updates `isReferentiallyTransparentFunctionComponent()` to check for `propTypes`.
> Components that use propTypes are not referentially transparent

- docs/API.md
- src/__tests__/setDisplayName-test.js
- src/__tests__/setPropTypes-test.js
- src/__tests__/setStatic-test.js
- src/index.js
- src/setDisplayName.js
- src/setPropTypes.js
- src/setStatic.js
Adds some static property helpers that look like higher-order component helpers (curried and component-last) but are used to mutate the base component rather than return a new component.
- `setStatic()`
- `setPropTypes()`
- `setDisplayName()`
> Static property helpers

- README.md
- src/packages/rx-recompose/README.md
- src/packages/rx-recompose/__tests__/createEventHandler-test.js
- src/packages/rx-recompose/__tests__/observeProps-test.js
- src/packages/rx-recompose/createEventHandler.js
- src/packages/rx-recompose/index.js
- src/packages/rx-recompose/observeProps.js
- src/packages/rx-recompose/package.json
RxJS bindings for Recompose and React.
Includes a helper called `observeProps()`. Very similar to `mapProps()`—instead of mapping owner props to child props, it maps a *sequence* of owner props to a sequence of child props.
```js
observeProps($ownerProps => $childProps)
```
Also includes `createEventHandler()`, which is a shortcut for creating a subject that pushes new values whenever it is called as a function.
This is essentially a port of my [react-rx-component](https://github.com/acdlite/react-rx-component) project, which I will deprecate in favor of this.
> New package: rx-recompose

- docs/API.md
- src/packages/recompose/__tests__/componentFromProp-test.js
- src/packages/recompose/__tests__/createSpy-test.js
- src/packages/recompose/componentFromProp.js
- src/packages/recompose/index.js
```js
componentFromProp(propName: string): ReactElementType
```
Creates a component that accepts a component as a prop and renders it with the remaining props.
Example:
```js
const Button = defaultProps(
{ component: 'button' },
componentFromProp('component')
);
<Button foo="bar" /> // renders <button foo="bar" />
<Button component="a" foo="bar" />  // renders <a foo="bar" />
<Button component={Link} foo="bar" />  // renders <Link foo="bar" />
```
> New util: componentFromProp()

- docs/API.md
Since the second argument of `branch` should be a HoC, I've wrapped `BaseComponent` inside a HoC using `renderComponent`.
Also, if `Post` is to be a component, then the curried `branch` function needs to be invoked with a component. In the example, I've used `renderNothing()` as this component.
However, using `branch` like this kinda of feels hacky--especially with using `renderNothing()` as its BaseComponent--but it does produce the desired effect of the `conditional()` mentioned in issue #21.
> correct renderComponent() example

- karma.conf.js
- src/packages/rx-recompose/README.md
- src/packages/rx-recompose/__tests__/observeProps-test.js
- src/packages/rx-recompose/observeProps.js
Updates the type signature of the `mapPropsStream` of `observeProps`:
```js
observeProps(
mapPropsStream: (props$: Observable) => Observable | { [propKey: string]: Observable },
BaseComponent: ReactElementType
): ReactElementType
```
In the new second form, an object of streams is turned into an stream of objects. To illustrate, the following two `mapPropsStream()` functions are equivalent:
```js
const mapPropsStream1 = () => Observable.just({ a, b, c }),
// Same as
const mapPropsStream2 = () => ({
a: Observable.just(a),
b: Observable.just(b),
c: Observable.just(c)
})
```
The second form is often more convenient because it avoids the need for `Observable.combineLatest`, but note that it is also more limiting: you must explicitly declare every prop that is passed to the base component. …
> Allow mapPropsStream to return an object of streams

- src/packages/recompose/createHelper.js
Fixes https://github.com/acdlite/recompose/issues/55
> Fix currying in production

- docs/API.md
- src/packages/recompose/__tests__/mapPropsOnChange-test.js
- src/packages/recompose/mapPropsOnChange.js
Change mapPropsOnChange so that propsMapper only receives the dependent props. Resulting object is combined with non-dependent props.
Closes #60
> Fix mapPropsOnChange

- README.md
Hi,
Just a small typo fix in README regarding the use of withReducer.
> Fix typo in withReducer example in README

- docs/API.md
> fixing 2 small typos in API.doc

- src/packages/rx-recompose/README.md
```javascript
return {
increment: Observable.just(increment$),
decrement: Observable.just(decrement$),
count: count$
}
```
instead of 
```javascript
return {
increment: Observable.just(increment$),
decrement: Observable.just(decrement$),
count
}
```
in rx-recompose Readme demo.
> Fix variable name error

- src/packages/recompose/__tests__/renderComponent-test.js
- src/packages/recompose/createHelper.js
- src/packages/recompose/renderComponent.js
When fully applied, `renderComponent()` should return a component, not an element.
> Fix render component & test

- src/packages/recompose/withState.js
Most functions in recompose can be required from ES5 code:
```js
const compose = require('recompose/compose')
```
But not `withState`.
```js
const withState = require('recompose/withState')
```
```js
withState('a', 'b', 0) // ERROR: withState is not a function
```
This is because `withState.js` exports more than one thing.
> Allow `withState` to be required by ES5 code

- src/packages/recompose/lifecycle.js
Some of our engineers passed `null` to `lifecycle()` instead of a no-op function `() => { }` or `_.noop`. This caused a run-time error in our staging environment.
This PR makes it allow falsy value to be a synonym for no-op. An alternative solution is to validate the arguments and throw immediately, so that these errors could be caught early.
> lifecycle: Allow `null` in place of `() => {}`

- src/packages/recompose/createHelper.js
- src/packages/recompose/package.json
Re https://github.com/acdlite/recompose/pull/92#issuecomment-181163598:
Lodash 4.3.0 fixes the incorrect curry behavior. This bumps Lodash and reverts 07c1564.
I know that @acdlite proposed [not using Lodash's curry at all](https://github.com/acdlite/recompose/pull/92#issuecomment-181189168), but here's a simpler change in the meantime.
> Bump lodash and revert to correct curry behavior

- karma.conf.js
- src/packages/recompose-relay/__tests__/recomposeRelay-test.js
- src/packages/rx-recompose/__tests__/observeProps-test.js
- src/packages/rx-recompose/observeProps.js
This should already be fixed in upcoming rewrite of rx-recompose (currently available as `rx-recompose@next` on npm).
> observeProps should block render until stream starts emitting props

- src/packages/recompose/__tests__/mapPropsOnChange-test.js
- src/packages/recompose/mapPropsOnChange.js
https://github.com/acdlite/recompose/pull/104#issuecomment-201820358
IMHO `omit` should be removed.
I'll explain why:
One of my most used construction with `mapPropsOnChange` was
```javascript
mapPropsOnChange(
['a', 'b', 'c'], 
({...props, a, b ,c}) => ({
...props,
someResult: blabla(a,b,c)
})
),
```
spread operator allows me to not lost `a,b,c` in the future, and reuse them again.
Now to make this work I can't use spread operator at all, because other props out of selection array i.e. ['a', 'b', 'c'] will be placed in `this.computedProps` so will be outdated. 
The code above after this [PR](https://github.com/acdlite/recompose/pull/104) now looks like
```javascript
mapPropsOnChange(
['a', 'b', 'c'], 
({a, b ,c}) => ({
a,
b,
c,
someResult: blabla(a,b,c)
})
),
```
So every time I add …
> removing omit

- src/packages/recompose/__tests__/mapPropsOnChange-test.js
This PR shows an unexpected behavior of `mapPropsOnChange`.
Please see #119
> Add a test for mapPropsOnChange

- .travis.yml
- package.json
[`codecov.io`](https://github.com/cainus/codecov.io) is deprecating, so it might be better to switch to [`codecov`](https://github.com/codecov/codecov-node).
> Use codecov instead of codecov.io

- src/packages/rx-recompose/README.md
- src/packages/rx-recompose/__tests__/createEventHandler-test.js
- src/packages/rx-recompose/__tests__/mapPropsStream-test.js
- src/packages/rx-recompose/__tests__/observeProps-test.js
- src/packages/rx-recompose/createComponent.js
- src/packages/rx-recompose/createEventHandler.js
- src/packages/rx-recompose/index.js
- src/packages/rx-recompose/mapPropsStream.js
- src/packages/rx-recompose/observeProps.js
The `next` branch has some nice improvements, but they won't be released until RxJS 5 is finalized. In the meantime, we should port those improvements over to master.
> Pull in API changes from next branch

- src/packages/recompose/__tests__/withHandlers-test.js
It seems like the immutability of handlers passed by `withHandlers` is not tested, is it?
> Test immutability of handlers passed by withHandlers

- src/packages/recompose/__tests__/flattenProp-test.js
- src/packages/recompose/flattenProp.js
Connects #190 
There is one issue that has not resolved. If the flatten prop has a key with the same name of the prop, it will be overwritten. As shown on second test case of `flattenProp-test.js`.
Any suggestion on solving this?
> changed flattenProp hoc it does not omit flattened prop

- docs/API.md
I found broken link in API TOC.
> Fix document `createEagerFactory` tilte

- docs/API.md
Adding `identity` function on the `branch` example code.
I got confused for `branch` function's document and example and I could understood this with issue https://github.com/acdlite/recompose/issues/109#issuecomment-214923584.
> Add identity function to example code

- src/packages/recompose/__tests__/mapPropsStream-test.js
- src/packages/recompose/componentFromStream.js
- src/packages/recompose/createEventHandler.js
- src/packages/recompose/mapPropsStream.js
- src/packages/recompose/setObservableConfig.js
Because mapPropsStream composes componentFromStream, the global observable transforms were being applied twice. We'll fix by exporting a factory version of each observable util (including componentFromStream) that allows you opt-out of the global transform.
This was not caught earlier because the tests for mapPropsStream use RxJS 5, which is not affected by double transforms because its observables are ES observables, anyway. To protect against regressions, we'll switch to testing with RxJS4 for now.
Keeping the new factory functions private for now so this can go out as a patch release.
> Fix mapPropsStream applying transforms twice

- package.json
Dumb small pull request but `babel-register` isn't in `package.json` so `npm test` was failing. Added it.
> Add babel-register to devDependencies

- src/packages/recompose/__tests__/withHandlers-test.js
The `react-unknown-props` warning occurs before `withHandler`'s warning, so the test is failed.
```
1. withHandlers-test › withHandlers warns if handler is not a higher-order function
t.is(error.firstCall.args[0], 'withHandlers(): Expected a map of higher-order functions. Refer to ' + 'the docs for more info.')
|
"Warning: Unknown prop `foo` on <button> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop\n    in button (created by withHandlers(button))\n    in withHandlers(button) (created by Unknown)\n    in Unknown"
```
This is a quick fix for helping CI back to normal. There are still `react-unknown-props` warnings in other tests.
> Fix a react-unknown-props warning

- src/packages/recompose/__tests__/branch-test.js
- src/packages/recompose/branch.js
> default third argument of branch to identity function

- docs/API.md
The signature of `withPropsOnChange` contained the new name `shouldMapOrKeys`, while the explanation referred `dependentPropKeys`.
> Update dependentPropKeys to shouldMapOrKeys in API docs.

- README.md
I found README's `API Documentaion` link got broken.
> Fix API Documentation Link

- package.json
- src/packages/recompose/__tests__/branch-test.js
- src/packages/recompose/__tests__/createHelper-test.js
- src/packages/recompose/branch.js
- src/packages/recompose/createHelper.js
Failing example
branch caused a console.error at createHelper as functions with default arguments returns incorrect length of arguments.
So [this](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/createHelper.js#L21) was true for branch when all arguments were provided
> Remove function and arguments length check in createHelper

- src/packages/recompose/__tests__/withReducer-test.js
- src/packages/recompose/withReducer.js
fixes #247 
See linked issue for reasons of this change
> withReducer: optionally initialize state from default reducer argument

- src/packages/recompose/branch.js
Not sure you would want to merge this but at least, I will learn something out of the discussion!
Currently, `branch` returns a full-fledged React component. I am wondering wether it could return a stateless functional component instead (which is interesting because the component could be eagerly rendered).
That would essentially mean that we would be fine with factories being (lazily) initialized in `render` instead of the component's constructor and the `willComponentReceiveProps` hook—is it the case?
> Make branch return a stateless functional component

- package.json
- src/packages/recompose/mostObservableConfig.js
- src/packages/recompose/package.json
Version 1.0 of symbol-observable is only breaking if it would be used with `require('symbol-observable')`, as recompose already uses es6 it can be upgraded without running into this breaking change as babel is already taking care about the default export.
All other changes should not affect recompose.
Here is the changelog:
https://github.com/blesh/symbol-observable/blob/master/CHANGELOG.md
IT would be nice to do this, as currently having redux and recompose in a project, results in two versions of `symbol-observable` being bundled.
Fixes #246
> Update symbol-observable to 1.0

- src/packages/recompose/compose.js
> Simplified the composer to use higher order components

- src/packages/recompose/__tests__/renderNothing-test.js
- src/packages/recompose/renderNothing.js
Fixes #288 
The problem that `renderNothing` mostly used with `branch` component, 
and since in release 0.21.0 branch does not create a class, 
we have that functional component returns null, what is prohibited with React 0.14.x and only possible with https://github.com/facebook/react/releases/tag/v15.0.0
Also as renderNothing is always a `terminator` so it should not cause perf issues.
PS: not possible to write test, I have no knowledge how to have few react versions simultaneously
> Make renderNothing as a classComponent

- docs/API.md
- src/packages/recompose/__tests__/withHandlers-test.js
- src/packages/recompose/withHandlers.js
Partially the same reason as `mapStateToProps` in react-redux  allows return a factory. 
To have ability to use local selectors see [reselect](https://github.com/reactjs/reselect) (memoization, cache) 
Like 
```javascript
withHandlers((/* initialProps */) => {
const selector_ = createSelector(({ x }) => x, x => someCalculus(x));
return {
getMemoizedResult: () => selector_,
};
})
```
This is somehow similar to `withPropsOnChange` but here you can use memoized data on demand.
The other case is to hold internal state which must not cause `setState` calls, like references, for which currently people try to use different hacks with recompose. (In my case `scrollTop` from scroll events) 
```javascript
withHandlers((/* initialProps */) => {
let ref_;
// let handle_;
return {
registerChild: () => …
```
> Allow handlers property of withHandlers to be a factory functions

- package.json
- src/packages/recompose/__tests__/createElement-test.js
- src/packages/recompose/__tests__/defaultProps-test.js
- src/packages/recompose/__tests__/flattenProp-test.js
- src/packages/recompose/__tests__/hoistStatics-test.js
- src/packages/recompose/__tests__/lifecycle-test.js
- src/packages/recompose/__tests__/mapProps-test.js
- src/packages/recompose/__tests__/onlyUpdateForKeys-test.js
- src/packages/recompose/__tests__/onlyUpdateForPropTypes-test.js
- src/packages/recompose/__tests__/pure-test.js
- src/packages/recompose/__tests__/renameProp-test.js
- src/packages/recompose/__tests__/renameProps-test.js
- src/packages/recompose/__tests__/renderComponent-test.js
- src/packages/recompose/__tests__/shouldUpdate-test.js
- src/packages/recompose/__tests__/toClass-test.js
- src/packages/recompose/__tests__/withContext-test.js
- src/packages/recompose/__tests__/withHandlers-test.js
- src/packages/recompose/__tests__/withProps-test.js
- src/packages/recompose/__tests__/withPropsOnChange-test.js
- src/packages/recompose/__tests__/withReducer-test.js
- src/packages/recompose/__tests__/withState-test.js
Few screens of tests warning like
```
Warning: Unknown prop `blabla` on <blublu> tag. 
Remove this prop from the element. 
For details, see https://fb.me/react-unknown-prop
```
has fixed (removed).
Ava updated.
> Remove all Unknown prop warning from tests

- src/packages/recompose/rxjsObservableConfig.js
This PR adds a `toESObservable` function to the `rxjsObservableConfig`, so it can be used with `componentFromStreamWithConfig`. I ran into this issue writing a library with recompose and RxJS. I don't want the library overwrite if someone has set the global config, but using `rxjsObservableConfig` with `componentFromStreamWithConfig` will throw an error, because `toESObservable` isn't defined.
It seems the tests for `componentFromStream` are skipped, so I didn't add a test for this case. Let me know if there's anything else I should add to this PR. Thanks.
> Add toESObservable identity fn to rxjsObservableConfig

- src/packages/recompose/__tests__/toClass-test.js
- src/packages/recompose/toClass.js
Using the `toClass` function to create a component using a string it create a component with the `baseComponent` variable not resolved, so if I try to create a component calling: `toClass('textarea')` I will receive as output a `<baseComponent>` element and not a `<textarea>` element.
> Change string component creation using React.createElement in toClass function

- docs/API.md
- src/packages/recompose/__tests__/componentFromStream-test.js
As from 0.22.0 `componentFromStream` will complete the stream during unmount and usage of [first](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-first), [last](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-last) or [single](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-single) methods can potentially throw [EmptyError](http://reactivex.io/rxjs/class/es6/util/EmptyError.js~EmptyError.html).
See #220 and #303
> componentFromStream can potentially throw EmptyError: no elements in sequence

- docs/API.md
Adding a note to clear things up with using state in `lifecycle`.
I was trying to implement an async data loading component and the doc doesn't say anything about how `this.state` is handled which is confusing. So I had to read the source code to determine if state changes were propagated. As suspected it does and that fact should be included in the docs.
> add note for the use of setState in lifecycle

- src/packages/recompose/lifecycle.js
The reason: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass
Removing `createClass` at all from `lifecycle`.
(importing it from `create-react-class` will cause current package incompatibility with React 14, and all that `require` with version check is not better than current solution )
Also IMO `lifecycle` must be deprecated or even removed from recompose.
And yes possibly breaking change.
> Fix lifecycle to support React 15.5

- package.json
For now it tries to run tests in lib folder.
> Fix jest config to search tests in src folder only

- README.md
Since we have es2015 modules support, current size optimization suggestion is outdated and gives not the best result.
> Update "Optimizing bundle size" README section

- docs/API.md
- src/packages/recompose/__tests__/lifecycle-test.js
With `v0.23.0` `createClass` was replaced with `Component` but some docs where not updated.
> Change createClass to Component in docs

- src/packages/recompose/lifecycle.js
Fixes 'regression' introduced in - https://github.com/acdlite/recompose/pull/346 , which also should result in some minor perf/memory gain as `spec` gets shared on the prototype now and this needs to be done only once.
cc @istarkov
> Fixed lack of es6 Object.assign in target envs like IE11

- package.json
It will guard contributors before commiting with lint errors.
> Run eslint on staged files as part of the precommit hook

- types/flow-typed/recompose_v0.24.x-/flow_v0.49.x-/recompose_v0.24.x-.js
- types/flow-typed/recompose_v0.24.x-/flow_v0.49.x-/test_withProps.js
...since `withProps` accepts an object too.
Added a test but I'm a bit of a flow n00b, and didn't have much success running the tests with flow-typed to see if it was working as expected (think it's to do with the flow-type CLI hitting GitHub, will chase up there) 🤔
> Fix withProps type def

- README.md
See [React.PureComponent](https://facebook.github.io/react/docs/react-api.html#react.purecomponent).
May also consider removing the reference to the deprecated [`PureRenderMixin`](https://facebook.github.io/react/docs/pure-render-mixin.html).
> docs(readme): refer pure to React.PureComponent

- src/packages/recompose/isClassComponent.js
Instead of checking for the `isReactComponent` property (which is internal to React), it seems advantageous to check for `render()`. This improves Preact support (when using recompose with non-preact-compat components) but also importantly works with components that don't inherit from `Component`.
> Simpler classful component check (fixes #458)

- src/packages/recompose/__tests__/createElement-test.js
- src/packages/recompose/__tests__/hoistStatics-test.js
- src/packages/recompose/__tests__/isReferentiallyTransparentFunctionComponent-test.js
- src/packages/recompose/__tests__/renameProp-test.js
- src/packages/recompose/__tests__/renameProps-test.js
- src/packages/recompose/isReferentiallyTransparentFunctionComponent.js
- src/packages/recompose/utils/createEagerElementUtil.js
As discussed in #442.
* We don't care about `propTypes` check anymore since it's already no-op in prod env.
* Notice few `shallow` → `mount` changes in tests – that's actually the confusion which I described in corresponding issue.
:v:
> Use eager factory optimization only in production env (close #442)

- src/packages/recompose/__tests__/withStateHandlers-test.js
- src/packages/recompose/withStateHandlers.js
Fixes #456 
Problem example
https://codesandbox.io/s/DRQ8y0zBx
Console output 
```
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `target` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
```
> Allow to use withStateHandlers with SyntheticEvents

- README.md
New jsfiddle uses built-in babel mode with syntax highlighting, as mentioned in #486.
This new fiddle uses the latest version of Recompose, and the example uses `withStateHandlers` rather than `compose`, `withState`, and `withHandlers`.
Code formatted externally with Prettier (default config, using online sandbox).
> Updated jsfiddle example base link. Fixes #486

- docs/API.md
> Clarify withStateHandlers behavior

- src/packages/recompose/package.json
- src/packages/recompose/yarn.lock
Updates hoist-non-react-statics to version 2. This brings the version range in line with react-redux's dependency on hoist-non-react-statics, allowing build tooling to dedupe and produce smaller bundles.
> hoist-non-react-statics@2.3.1

- src/packages/recompose/package.json
> Allow React 16

- README.md
Base fiddle was using a unpkg link pointed at the old (React 15) dist url but without a React version, so broke with the release of React 16. Now points to the correct location for React 16, with 16 specified (shouldn't break this way again).
> Updated base fiddle link

- docs/API.md
Hello,
What do you think about adding example for `lifecycle` usage. When I first used it, it wasn't clear that I should use `this` inside spec methods. 
Also is there a reason for defining `lifecycle` like this? It feels strange to use `this` in all this functional composition. I was thinking if it would be better if spec functions would get props and some `setState` equivalent method as arguments? It will increase API surface but I think it would be more consistent with other methods.
> add lifecycle example in docs

- scripts/getPackageNames.js
Running yarn 1.0 in the recompose repo causes the `installNestedPackageDeps` script to run forever in a loop because it tries to run `yarn` in the `src/packages/rx-recompose` directory, which doesn't have a `package.json` file, which causes the dependencies to be installed in the root project, triggering the already executing postinstall script again and again.
If you'd prefer I can just remove the `src/packages/rx-recompose` directory, but perhaps there's a reason it's still there.
> filter packages by the existence of a package.json file

- README.md
> Fix babel-plugin-lodash name on readme

- docs/API.md
- src/packages/recompose/__tests__/withReducer-test.js
- src/packages/recompose/withReducer.js
I thought of this after looking at `withState`, which provides `stateUpdater` methods that can take in callbacks. My rationale for allowing for an optional callback that receives the new state for the `dispatch` method that `withReducer` provides is that after calculating the new state, you might want to propagate state changes elsewhere. Maybe you need to call a given `onChange` prop or handle some other side effect like that.
We _could_ just execute the reducer with the old state and the action to generate the new state outside of the `dispatch` call, but I find it _really_ clunky to calculate the new state twice - once implicitly as a result of the `dispatch` call and once explicitly by executing the reducer - in order to address these types of scenarios. I am also not a fan of …
> Adding an optional callback argument to the `dispatch` method provided by `withReducer`

- src/packages/recompose/nest.js
This is an error I ran into while statically analyzing this code. 
In newer versions of `babylon` it will error if the rest param is not the end when desctructuring.
See here: https://github.com/babel/babylon/blob/master/CHANGELOG.md#eyeglasses-spec-compliancy-6
> Object Rest/Spread compliance

- src/packages/recompose/__tests__/hoistStatics-test.js
- src/packages/recompose/hoistStatics.js
[hoist-non-react-statics](https://github.com/mridgway/hoist-non-react-statics) supports an [undocumented argument `blacklist`](https://github.com/mridgway/hoist-non-react-statics/blob/master/src/index.js#L34) in order to blacklist static properties that shall not be copied.
This PR adds that option to `recompose/hoistStatics`.
> Pass blacklist argument to hoist-non-react-statics using hoistStatics

- .prettierrc
- package.json
- scripts/jest.setup.js
- src/packages/recompose/__tests__/componentFromStream-test.js
- src/packages/recompose/__tests__/withStateHandlers-test.js
- src/packages/recompose/package.json
- src/packages/recompose/yarn.lock
- yarn.lock
In order to provide changes came in React 16.3 here is dependencies and tests update.
To simplify next commits.
> Update dependencies before changes according to React 16.3+

- src/packages/recompose/__tests__/withHandlers-test.js
- src/packages/recompose/__tests__/withPropsOnChange-test.js
- src/packages/recompose/createSink.js
- src/packages/recompose/withHandlers.js
- src/packages/recompose/withPropsOnChange.js
In async mode `propsMapper` in `withPropsOnChange` can be called multiple times
it can be avoided using memoize see this commit https://github.com/acdlite/recompose/pull/647/commits/83fc7cadb0af2ef29fd3abbb0a37e634ab5ceddf
but it does not solve some edge cases as memoize will work on all `props` so multiple calls will still be possible. So I think to remove it.
> New lifecycles support

- docs/API.md
- src/packages/recompose/__tests__/withRenderProps-test.js
- src/packages/recompose/index.js
- src/packages/recompose/withRenderProps.js
From this [tweet](https://twitter.com/icelabaratory/status/992123859590631424). Let me know if there's anything missing.
> Add withRenderProps

- .travis.yml
Fixes issue with webpack 2.7.0 -> upath <1.0.5 dependency, which incorrectly specifies compatibility with node <= 9
Issue described here: https://github.com/anodynos/upath/pull/15 and fixed here https://github.com/anodynos/upath/commit/8c5f4e10376ed1cd4553d9432297d39a34410c69#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 (released as 1.0.5)
Kind of hacky but this unblocks CI until travis's yarn stops resolving the older version. It's 1.0.5 on my local so I'm not 100% sure what travis's problem is.
> yarn --ignore-engines on travis CI (which runs node 10)

- src/packages/recompose/__tests__/compose-test.js
- src/packages/recompose/compose.js
Hi. it's not a issue, but made simple compose without 'if'. thanks.
> better compose

- .size-snapshot.json
- docs/API.md
- src/packages/recompose/__tests__/fromRenderProps-test.js
- src/packages/recompose/__tests__/types/test_fromRenderProps.js
- src/packages/recompose/fromRenderProps.js
- src/packages/recompose/index.js.flow
Add support for multiple arguments in `fromRenderProps` HOC.
for issue #693
> feat(fromRenderProps): add support for multiple arguments (Apollo usecase) #693

- README.md
Switch unpkg link of recompose from https://unpkg.com/recompose/build/Recompose.js to https://unpkg.com/recompose/dist/Recompose.umd.js
fixed #691
> docs: use Recompose.umd.js file in jsfiddle

- .size-snapshot.json
- src/packages/recompose/__tests__/withPropsOnChange-test.js
- src/packages/recompose/withPropsOnChange.js
In continuation to the discussion in https://github.com/acdlite/recompose/issues/666.
Saving prevProps returns the HOC to it's original behavior before the lifecycle updates.
Added test case that fails with the current implementation and passes with the fix.
> Fix withPropsOnChange shouldMap consistency

- LICENSE.md
- scripts/release.js
Also, update the license dates.
For legal purposes, it's often preferable to have the actual license file. See also e.g. https://github.com/lerna/lerna/pull/1465.
> Include license in published packages

- scripts/release.js
Fixes https://github.com/acdlite/recompose/issues/717
By default babel only copies `*.js` files when passing in a whole directory. Instead of globbing for `*.js` files, just pass the entire `sourceDir` as input and configure babel to also ignore `node_modules`. This should preserve the folder structure.
I went to remove `glob` as a dep but couldn't find it listed as a dependency anywhere.
> Preserve folder structure during build

- .size-snapshot.json
- src/packages/recompose/withStateHandlers.js
Removed optimisation is useless in React 16. The only intent for it was to not update if null was returned in handler. 
But returning same value didn't caused update too, this is not same as React setState works.
This is possibly a breaking change.
> Remove useless optimisation

- .size-snapshot.json
- src/packages/recompose-relay/yarn.lock
- src/packages/recompose/package.json
- src/packages/recompose/shallowEqual.js
- src/packages/recompose/yarn.lock
- yarn.lock
Remove shallowEquals import from fbjs and just copy the function  #here
Fix #742 using solution from @gaearon (copy/paste)
> Remove fbjs dependency

- README.md
As @trueadm wrote [in this issue](https://github.com/reactjs/reactjs.org/issues/639#issuecomment-367858928) on React documentation, the future performance optimizations mentioned in readme file are already there. 🎉 
> Functional components in React 16 don't go through the same code path as class components, unlike in previous version where they were converted to classes and would have the same code path. Class components have additional checks required and overhead in creating the instances that simple functions don't have.
> Update README.md to reflect performance changes in React 16

- src/packages/recompose/index.js.flow
Allows downstream dependencies to enable the flow nonstrict-import rule
> Enable flow strict
